runtime: go112

includes:
  - env_variables.yaml

handlers:
- url: /scripts
  static_dir: static/scripts

# Use HTTPS for all requests.
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
